---
title: "Overview"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 1
    #code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```

# Geography of Catchment

```{r, echo=FALSE, warning=FALSE, message=FALSE}
# Load our libraries & key datasets

library(sf)
library(tidyverse)
library(DT)

 catch <- read_sf("/dbfs/mnt/lab/unrestricted/harry.gray@enivronment-agency.gov.uk/Interim_WFD_2022.shp")# Catchment shapefiles

  CAT <- catch[catch$OPCAT_NAME == "Brue and Axe",]
  
  CAT_Union <- CAT %>% st_union()
  
 

```


Random text


```{r echo=FALSE, warning=FALSE, message=FALSE}
library(magrittr)
library(ggspatial)


#Load in files
  DRN <- read_sf("/dbfs/mnt/lab/unrestricted/harry.gray@enivronment-agency.gov.uk/DRN/DRN_Merged_MCAT.shp")
  Rivers_250k <- read_sf("/dbfs/mnt/lab/unrestricted/harry.gray@enivronment-agency.gov.uk/CEP/Hydrology/Rivers_250k.shp")



# Transform crs so all interoperable and work with basemaps crs which is 3857 and crop to chosen catchment
  
  CAT %<>% st_transform(st_crs(3857))
  
  Rivers_250 <-  Rivers_250k %>% 
    st_transform(st_crs(3857)) %>% 
    st_intersection(CAT)
  
# Generate the basemap

  #bbox <- st_bbox(CAT)

#   basemaps::set_defaults(map_service = "carto", map_type = "voyager")
 #  Base_basemaps <-  basemaps::basemap_ggplot(ext=bbox, verbose=FALSE)
    
# Plot the basemap + above spatial data

#Base_basemaps+
  ggplot()+
  geom_sf(data=CAT, col="black", fill=NA)+geom_sf(data=Rivers_250, col="steelblue")+
  theme_void()+
  annotation_scale(location = "bl", width_hint = 0.5)+
  annotation_north_arrow(location = "bl", which_north = "true", 
                         pad_x = unit(0.75, "in"), pad_y = unit(0.5, "in"),
                         style = north_arrow_fancy_orienteering)+
  labs(title = paste0(CAT$OPCAT_NAME, " and rivers at 250k"),
       caption = "note, smaller streams are not shown at this resolution")
       
```

The Brue & Axe catchment is located in xXx.

# Topography

```{r}

library(elevatr)

# CAT %<>% st_transform(st_crs(4326))
 
elev_rast <- elevatr::get_elev_raster(CAT, z=9, clip="locations")

elev_rast_df <- as.data.frame(raster::rasterToPoints(elev_rast))
colnames(elev_rast_df) <- c("x", "y", "Elev")
  
DRN_OPO <- DRN %>% filter(OPCAT_NAME == "Brue and Axe")

ggplot(data = NULL) +
  geom_raster(data = elev_rast_df, aes(x = x, y = y, fill = Elev)) +
  geom_sf(data = CAT_Union, col = 1, fill = NA) +
  geom_sf(data= DRN_OPO, col="#3944bc", fill=NA) +
  scale_fill_gradientn(colours = terrain.colors(200)) +  # Use 100 colors for the gradient
  labs(fill = "Elevation (m)") +
  theme_void()+
   annotation_scale(location = "bl", width_hint = 0.5)+
  annotation_north_arrow(location = "bl", which_north = "true", 
                         pad_x = unit(0.75, "in"), pad_y = unit(0.5, "in"),
                         style = north_arrow_fancy_orienteering)+
  labs(title = paste0(CAT$OPCAT_NAME, " Topographic Map"))


```

